CREATE TABLE IF NOT EXISTS reservation_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_time TIMESTAMP,
  created_by VARCHAR(255),
  drop_stop_id BIGINT,
  paid BOOLEAN,
  passenger_email VARCHAR(255),
  passenger_name VARCHAR(255),
  payment_method VARCHAR(255),
  payment_reference VARCHAR(255),
  pickup_stop_id BIGINT,
  schedule_id BIGINT NOT NULL,
  seat_number INT NOT NULL,
  status VARCHAR(32),
  username VARCHAR(255),
  cancelled_at TIMESTAMP
);

-- Optional non-unique index for faster lookups
CREATE INDEX IF NOT EXISTS idx_res_hist_sched_seat ON reservation_history (schedule_id, seat_number);
CREATE INDEX IF NOT EXISTS idx_res_hist_username ON reservation_history (username);